var search_exchange_years = [
    new COMMON_CODE(null, 'search_year', '년')
    , new COMMON_CODE('2021', '2021', '2021년')
    , new COMMON_CODE('2020', '2020', '2020년')
    , new COMMON_CODE('2019', '2019', '2019년')
];

var search_exchange_months = [
    new COMMON_CODE(null, 'search_month', '월')
    , new COMMON_CODE('12', '12', '12월')
    , new COMMON_CODE('11', '11', '11월')
    , new COMMON_CODE('10', '10', '10월')
    , new COMMON_CODE('9', '09', '9월')
    , new COMMON_CODE('8', '08', '8월')
    , new COMMON_CODE('7', '07', '7월')
    , new COMMON_CODE('6', '06', '6월')
    , new COMMON_CODE('5', '05', '5월')
    , new COMMON_CODE('4', '04', '4월')
    , new COMMON_CODE('3', '03', '3월')
    , new COMMON_CODE('2', '02', '2월')
    , new COMMON_CODE('1', '01', '1월')
];

var search_exchange_type = [
    new COMMON_CODE(null, 'search_type', '검색조건')
    , new COMMON_CODE('all', '', '검색조건')
    , new COMMON_CODE('mem_no', 'mem_no', '회원번호')
    , new COMMON_CODE('mem_id', 'user_id', 'User ID')
    , new COMMON_CODE('mem_nick', 'mem_nick', 'User 닉네임')
    , new COMMON_CODE('mem_phone', 'mem_phone', '연락처')
]

var search_exchange_state = [
    new COMMON_CODE(null, 'search_state', '처리상태')
    , new COMMON_CODE('all', '', '처리상태')
    , new COMMON_CODE('wait', '0', '미처리')
    , new COMMON_CODE('ok', '1', '완료')
    , new COMMON_CODE('reject', '2', '불가')
]

var inforex_bank_code = [
    new COMMON_CODE(null, 'bank_code', '은행코드')
    , new COMMON_CODE('39', '경남은행', '경남은행')
    , new COMMON_CODE('34', '광주은행', '광주은행')
    , new COMMON_CODE('4', '국민은행', '국민은행')
    , new COMMON_CODE('3', '기업은행', '기업은행')
    , new COMMON_CODE('11', '농협', '농협')
    , new COMMON_CODE('31', '대구은행', '대구은행')
    , new COMMON_CODE('55', '도이치은행', '도이치은행')
    , new COMMON_CODE('32', '부산은행', '부산은행')
    , new COMMON_CODE('61', '비엔피파리바은행', '비엔피파리바은행')
    , new COMMON_CODE('64', '산림조합중앙회', '산림조합중앙회')
    , new COMMON_CODE('2', '산업은행', '산업은행')
    , new COMMON_CODE('50', '저축은행', '저축은행')
    , new COMMON_CODE('45', '새마을금고중앙회', '새마을금고중앙회')
    , new COMMON_CODE('8', '수출입은행', '수출입은행')
    , new COMMON_CODE('7', '수협은행', '수협은행')
    , new COMMON_CODE('88', '신한은행', '신한은행')
    , new COMMON_CODE('48', '신협', '신협')
    , new COMMON_CODE('20', '우리은행', '우리은행')
    , new COMMON_CODE('71', '우체국', '우체국')
    , new COMMON_CODE('37', '전북은행', '전북은행')
    , new COMMON_CODE('35', '제주은행', '제주은행')
    , new COMMON_CODE('67', '중국건설은행', '중국건설은행')
    , new COMMON_CODE('62', '중국공상은행', '중국공상은행')
    , new COMMON_CODE('90', '카카오뱅크', '카카오뱅크')
    , new COMMON_CODE('89', '케이뱅크', '케이뱅크')
    , new COMMON_CODE('294', '펀드온라인코리아', '펀드온라인코리아')
    , new COMMON_CODE('27', '한국씨티은행', '한국씨티은행')
    , new COMMON_CODE('60', 'BOA은행', 'BOA은행')
    , new COMMON_CODE('54', 'HSBC은행', 'HSBC은행')
    , new COMMON_CODE('57', '제이피모간체이스은행', '제이피모간체이스은행')
    , new COMMON_CODE('81', '하나은행', '하나은행')
    , new COMMON_CODE('23', 'SC제일은행', 'SC제일은행')
    , new COMMON_CODE('247', 'NH투자증권', 'NH투자증권')
    , new COMMON_CODE('261', '교보증권', '교보증권')
    , new COMMON_CODE('267', '대신증권', '대신증권')
    , new COMMON_CODE('287', '메리츠종합금융증권', '메리츠종합금융증권')
    , new COMMON_CODE('238', '미래에셋대우', '미래에셋대우')
    , new COMMON_CODE('290', '부국증권', '부국증권')
    , new COMMON_CODE('240', '삼성증권', '삼성증권')
    , new COMMON_CODE('291', '신영증권', '신영증권')
    , new COMMON_CODE('278', '신한금융투자', '신한금융투자')
    , new COMMON_CODE('209', '유안타증권', '유안타증권')
    , new COMMON_CODE('280', '유진투자증권', '유진투자증권')
    , new COMMON_CODE('265', '이베스트투자증권', '이베스트투자증권')
    , new COMMON_CODE('292', '케이프투자증권', '케이프투자증권')
    , new COMMON_CODE('264', '키움증권', '키움증권')
    , new COMMON_CODE('270', '하나금융투자', '하나금융투자')
    , new COMMON_CODE('262', '하이투자증권', '하이투자증권')
    , new COMMON_CODE('243', '한국투자증권', '한국투자증권')
    , new COMMON_CODE('269', '한화투자증권', '한화투자증권')
    , new COMMON_CODE('263', '현대차증권', '현대차증권')
    , new COMMON_CODE('279', 'DB금융투자', 'DB금융투자')
    , new COMMON_CODE('218', 'KB증권', 'KB증권')
    , new COMMON_CODE('227', 'KTB투자증권', 'KTB투자증권')
    , new COMMON_CODE('266', 'SK증권', 'SK증권')
]
