package com.dalbit.payment.module.cnnew_v0003;

public class Common {
    public static final String RTN_ERR = "-1";
    public static final String RTN_OK = "0000";
    public static final String INVALID_PROPERTY = "9001";
    public static final String INVALID_LOGFILE = "9002";
    public static final String INVALID_SVRINFO = "9003";
    public static final String INVALID_VERINFO = "9004";
    public static final String INVALID_KEYINFO = "9005";
    public static final String INVALID_MODE = "9101";
    public static final String INVALID_RECORDKEY = "9102";
    public static final String INVALID_SVCID = "9103";
    public static final String INVALID_TRADEID = "9107";
    public static final String INVALID_MOBILID = "9109";
    public static final String INVALID_PRDTPRICE = "9110";
    public static final String INVALID_BILLKEY = "9111";
    public static final String INVALID_AUTHTYPE = "9112";
    public static final String INVALID_CURRENCY = "9113";
    public static final String INVALID_TAXDIV = "9114";
    public static final String INVALID_TAXPRICE = "9115";
    public static final String INVALID_TAXFREEPRICE = "9116";
    public static final String INVALID_NOINTFLAG = "9117";
    public static final String INVALID_CARDNO = "9118";
    public static final String INVALID_EXPRDT = "9119";
    public static final String INVALID_INTEREST = "9120";
    public static final String INVALID_CARDPW = "9121";
    public static final String INVALID_SOCIALNO = "9122";
    public static final String INVALID_POINTDIV = "9123";
    public static final String INVALID_AUTOBILLDATE = "9124";
    public static final String INVALID_PRDTNM = "9125";
    public static final String ERR_SOCKET = "9901";
    public static final String ERR_CONNECT = "9902";
    public static final String ERR_SEND = "9903";
    public static final String ERR_RECV = "9904";
    public static final String ERR_RECV_TIMEOUT = "9905";
    public static final String ERR_ETC = "9906";
    public static final String ERR_CLOSE = "9999";
    public static final int PACKET_RCV_SIZE = 400;
    public static final int PACKET_RCV_SIZE2 = 500;
    public static final int PACKET_RCV_SIZE3 = 510;
    public static final int PACKET_RCV_SIZE4 = 800;
    public static final int PACKET_RCV_SIZE5 = 1440;
    public static final int PACKET_RCV_SIZE6 = 268;
    public static final int PACKET_RCV_SIZE7 = 299;
}
