package com.dalbit.status.vo.procedure;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class P_PushStatusOutPutVo {

    private String the_date;
    private String bthe_date;
    private int the_hr;
    private int male_succ_cnt;
    private int male_fail_cnt;
    private int female_send_cnt;
    private int female_succ_cnt;
    private int female_fail_cnt;
    private int none_succ_cnt;
    private int none_fail_cnt;
    private int total_succ_cnt;
    private int total_fail_cnt;
    private String gb;
    private int p11Succ;
    private int p11Fail;
    private int p15Succ;
    private int p15Fail;
    private int p16Succ;
    private int p16Fail;
    private int p17Succ;
    private int p17Fail;
    private int p31Succ;
    private int p31Fail;
    private int p20Succ;
    private int p20Fail;
    private int p25Succ;
    private int p25Fail;
    private int p19Succ;
    private int p19Fail;
    private int p62Succ;
    private int p62Fail;
    private int p53Succ;
    private int p53Fail;
    private int p61Succ;
    private int p61Fail;
    private int totSucc;
    private int totFail;
    private int p18Succ;
    private int p18Fail;
    private int p30Succ;
    private int p30Fail;
    private int p24Succ;
    private int p24Fail;
    private int p21Succ;
    private int p21Fail;
    private int p22Succ;
    private int p22Fail;
    private int p23Succ;
    private int p23Fail;
    private int p32Succ;
    private int p32Fail;
    private int p33Succ;
    private int p33Fail;
    private int p51Succ;
    private int p51Fail;
    private int p52Succ;
    private int p52Fail;
    private int p60Succ;
    private int p60Fail;
    private int p63Succ;
    private int p63Fail;
    private int p50Succ;
    private int p50Fail;
    private int p54Succ;
    private int p54Fail;
    private int p55Succ;
    private int p55Fail;
    private int p56Succ;
    private int p56Fail;
    private int p57Succ;
    private int p57Fail;
    private int p58Succ;
    private int p58Fail;
    private int p92Succ;
    private int p92Fail;
    private int p93Succ;
    private int p93Fail;
    private int p94Succ;
    private int p94Fail;
    private int p95Succ;
    private int p95Fail;
    private int p96Succ;
    private int p96Fail;

    private int p34Succ;
    private int p34Fail;
    private int p35Succ;
    private int p35Fail;

    private String year;
    private String month;
    private String day;
    private String byear;
    private String bmonth;
    private String bday;


    private int male_alim_s;
    private int female_alim_s;
    private int none_alim_s;
    private int total_alim_s;
    private int male_alim_v;
    private int female_alim_v;
    private int none_alim_v;
    private int total_alim_v;
    private int male_alim_n;
    private int female_alim_n;
    private int none_alim_n;
    private int total_alim_n;

    private int bmale_alim_s;
    private int bfemale_alim_s;
    private int bnone_alim_s;
    private int btotal_alim_s;
    private int bmale_alim_v;
    private int bfemale_alim_v;
    private int bnone_alim_v;
    private int btotal_alim_v;
    private int bmale_alim_n;
    private int bfemale_alim_n;
    private int bnone_alim_n;
    private int btotal_alim_n;

    private String gender;
    private int Set_1y;
    private int Set_1n;
    private int rateSet_1y;
    private int rateSet_1n;
    private int sumSet_1y;
    private int sumSet_1yn;
    private int Set_2y;
    private int Set_2n;
    private int rateSet_2y;
    private int rateSet_2n;
    private int sumSet_2y;
    private int sumSet_2yn;
    private int Set_3y;
    private int Set_3n;
    private int rateSet_3y;
    private int rateSet_3n;
    private int sumSet_3y;
    private int sumSet_3yn;
    private int Set_4y;
    private int Set_4n;
    private int rateSet_4y;
    private int rateSet_4n;
    private int sumSet_4y;
    private int sumSet_4yn;
    private int Set_5y;
    private int Set_5n;
    private int rateSet_5y;
    private int rateSet_5n;
    private int sumSet_5y;
    private int sumSet_5yn;
    private int Set_6y;
    private int Set_6n;
    private int rateSet_6y;
    private int rateSet_6n;
    private int sumSet_6y;
    private int sumSet_6yn;
    private int Set_7y;
    private int Set_7n;
    private int rateSet_7y;
    private int rateSet_7n;
    private int sumSet_7y;
    private int sumSet_7yn;
    private int Set_8y;
    private int Set_8n;
    private int rateSet_8y;
    private int rateSet_8n;
    private int sumSet_8y;
    private int sumSet_8yn;
    private int Set_9y;
    private int Set_9n;
    private int rateSet_9y;
    private int rateSet_9n;
    private int sumSet_9y;
    private int sumSet_9yn;
    private int Set_10y;
    private int Set_10n;
    private int rateSet_10y;
    private int rateSet_10n;
    private int sumSet_10y;
    private int sumSet_10yn;
    private int Set_11y;
    private int Set_11n;
    private int rateSet_11y;
    private int rateSet_11n;
    private int sumSet_11y;
    private int sumSet_11yn;


}
