package com.dalbit.enter.vo.procedure;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class P_PaymentDayPaycodeOutputVo {
    private String the_date;    // 일자
    private int total_cnt;		// 총건
    private int total_cmt;		// 총수량
    private int total_amt;		// 총금액
    private int code01_cnt;     // code01결제건
    private int code01_cmt;     // code01결제수량
    private int code01_amt;     // code01결제금액
    private int code02_cnt;     // code02결제건
    private int code02_cmt;     // code02결제수량
    private int code02_amt;     // code02결제금액
    private int code03_cnt;     // code03결제건
    private int code03_cmt;     // code03결제수량
    private int code03_amt;     // code03결제금액
    private int code04_cnt;     // code04결제건
    private int code04_cmt;     // code04결제수량
    private int code04_amt;     // code04결제금액
    private int code05_cnt;     // code05결제건
    private int code05_cmt;     // code05결제수량
    private int code05_amt;     // code05결제금액
    private int code06_cnt;     // code06결제건
    private int code06_cmt;     // code06결제수량
    private int code06_amt;     // code06결제금액
    private int code07_cnt;     // code07결제건
    private int code07_cmt;     // code07결제수량
    private int code07_amt;     // code07결제금액
    private int code08_cnt;     // code08결제건
    private int code08_cmt;     // code08결제수량
    private int code08_amt;     // code08결제금액
    private int code09_cnt;     // code09결제건
    private int code09_cmt;     // code09결제수량
    private int code09_amt;     // code09결제금액
    private int code10_cnt;     // code10결제건
    private int code10_cmt;     // code10결제수량
    private int code10_amt;     // code10결제금액
    private int code11_cnt;     // code11결제건
    private int code11_cmt;     // code11결제수량
    private int code11_amt;     // code11결제금액
    private int code12_cnt;     // code12결제건
    private int code12_cmt;     // code12결제수량
    private int code12_amt;     // code12결제금액
    private int code13_cnt;     // code13결제건
    private int code13_cmt;     // code13결제수량
    private int code13_amt;     // code13결제금액
    private int code14_cnt;     // code14결제건
    private int code14_cmt;     // code14결제수량
    private int code14_amt;     // code14결제금액
    private int code15_cnt;     // code15결제건
    private int code15_cmt;     // code15결제수량
    private int code15_amt;     // code15결제금액
    private int code16_cnt;     // code16결제건
    private int code16_cmt;     // code16결제수량
    private int code16_amt;     // code16결제금액
    private int code17_cnt;     // code17결제건
    private int code17_cmt;     // code17결제수량
    private int code17_amt;     // code17결제금액
    private int code18_cnt;     // code18결제건
    private int code18_cmt;     // code18결제수량
    private int code18_amt;     // code18결제금액
    private int code19_cnt;     // code19결제건
    private int code19_cmt;     // code19결제수량
    private int code19_amt;     // code19결제금액
    private int code20_cnt;     // code20결제건
    private int code20_cmt;     // code20결제수량
    private int code20_amt;     // code20결제금액
    private int code21_cnt;     // code21결제건
    private int code21_cmt;     // code21결제수량
    private int code21_amt;     // code21결제금액
    private int code22_cnt;     // code22결제건
    private int code22_cmt;     // code22결제수량
    private int code22_amt;     // code22결제금액
    private int code23_cnt;     // code23결제건
    private int code23_cmt;     // code23결제수량
    private int code23_amt;     // code23결제금액
    private int code24_cnt;     // code24결제건
    private int code24_cmt;     // code24결제수량
    private int code24_amt;     // code24결제금액
    private int code25_cnt;     // code25결제건
    private int code25_cmt;     // code25결제수량
    private int code25_amt;     // code25결제금액
    private int code26_cnt;     // code26결제건
    private int code26_cmt;     // code26결제수량
    private int code26_amt;     // code26결제금액
    private int code27_cnt;     // code27결제건
    private int code27_cmt;     // code27결제수량
    private int code27_amt;     // code27결제금액
    private int code28_cnt;     // code28결제건
    private int code28_cmt;     // code28결제수량
    private int code28_amt;     // code28결제금액
    private int code29_cnt;     // code29결제건
    private int code29_cmt;     // code29결제수량
    private int code29_amt;     // code29결제금액
    private int code30_cnt;     // code30결제건
    private int code30_cmt;     // code30결제수량
    private int code30_amt;     // code30결제금액
    private int code31_cnt;     // code31결제건
    private int code31_cmt;     // code31결제수량
    private int code31_amt;     // code31결제금액
    private int code32_cnt;     // code32결제건
    private int code32_cmt;     // code32결제수량
    private int code32_amt;     // code32결제금액
    private int code33_cnt;     // code33결제건
    private int code33_cmt;     // code33결제수량
    private int code33_amt;     // code33결제금액
    private int code34_cnt;     // code34결제건
    private int code34_cmt;     // code34결제수량
    private int code34_amt;     // code34결제금액
    private int code35_cnt;     // code35결제건
    private int code35_cmt;     // code35결제수량
    private int code35_amt;     // code35결제금액
}
