package com.dalbit.enter.vo.procedure;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class P_PayCodeOutVo {
    private int sum_totalCnt;
    private int sum_totalAmt;
    private int sum_totalCmt;
    private int sum_code01Cnt;
    private int sum_code01Amt;
    private int sum_code01Cmt;
    private int sum_code02Cnt;
    private int sum_code02Amt;
    private int sum_code02Cmt;
    private int sum_code03Cnt;
    private int sum_code03Amt;
    private int sum_code03Cmt;
    private int sum_code04Cnt;
    private int sum_code04Amt;
    private int sum_code04Cmt;
    private int sum_code05Cnt;
    private int sum_code05Amt;
    private int sum_code05Cmt;
    private int sum_code06Cnt;
    private int sum_code06Amt;
    private int sum_code06Cmt;
    private int sum_code07Cnt;
    private int sum_code07Amt;
    private int sum_code07Cmt;
    private int sum_code08Cnt;
    private int sum_code08Amt;
    private int sum_code08Cmt;
    private int sum_code09Cnt;
    private int sum_code09Amt;
    private int sum_code09Cmt;
    private int sum_code10Cnt;
    private int sum_code10Amt;
    private int sum_code10Cmt;
    private int sum_code11Cnt;
    private int sum_code11Amt;
    private int sum_code11Cmt;
    private int sum_code12Cnt;
    private int sum_code12Amt;
    private int sum_code12Cmt;
    private int sum_code13Cnt;
    private int sum_code13Amt;
    private int sum_code13Cmt;
    private int sum_code14Cnt;
    private int sum_code14Amt;
    private int sum_code14Cmt;
    private int sum_code15Cnt;
    private int sum_code15Amt;
    private int sum_code15Cmt;
    private int sum_code16Cnt;
    private int sum_code16Amt;
    private int sum_code16Cmt;
    private int sum_code17Cnt;
    private int sum_code17Amt;
    private int sum_code17Cmt;
    private int sum_code18Cnt;
    private int sum_code18Amt;
    private int sum_code18Cmt;
    private int sum_code19Cnt;
    private int sum_code19Amt;
    private int sum_code19Cmt;
    private int sum_code20Cnt;
    private int sum_code20Amt;
    private int sum_code20Cmt;
    private int sum_code21Cnt;
    private int sum_code21Amt;
    private int sum_code21Cmt;
    private int sum_code22Cnt;
    private int sum_code22Amt;
    private int sum_code22Cmt;
    private int sum_code23Cnt;
    private int sum_code23Amt;
    private int sum_code23Cmt;
}
