package com.dalbit.enter.vo.procedure;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class P_PayInfoOutVo {

    private int total_cnt;
    private int total_amt;
    private int total_cmt;
    private int mc_cnt;
    private int mc_amt;
    private int mc_cmt;
    private int cn_cnt;
    private int cn_amt;
    private int cn_cmt;
    private int inapp_cnt;
    private int inapp_amt;
    private int inapp_cmt;
    private int gm_cnt;
    private int gm_amt;
    private int gm_cmt;
    private int hm_cnt;
    private int hm_amt;
    private int hm_cmt;
    private int gg_cnt;
    private int gg_amt;
    private int gg_cmt;
    private int gc_cnt;
    private int gc_amt;
    private int gc_cmt;
    private int tmoney_cnt;
    private int tmoney_amt;
    private int tmoney_cmt;
    private int cashbee_cnt;
    private int cashbee_amt;
    private int cashbee_cmt;
    private int payco_cnt;
    private int payco_amt;
    private int payco_cmt;
    private int kakaopay_cnt;
    private int kakaopay_amt;
    private int kakaopay_cmt;
    private int kakaomoney_cnt;
    private int kakaomoney_amt;
    private int kakaomoney_cmt;

    private int ra_cnt;
    private int ra_amt;
    private int ra_cmt;
    private int va_cnt;
    private int va_amt;
    private int va_cmt;
    private int male_cnt;
    private int male_amt;
    private int male_cmt;
    private int female_cnt;
    private int female_amt;
    private int female_cmt;
    private int none_cnt;
    private int none_amt;
    private int none_cmt;
    private int age00_cnt;
    private int age00_amt;
    private int age00_cmt;
    private int age10_cnt;
    private int age10_amt;
    private int age10_cmt;
    private int age20_cnt;
    private int age20_amt;
    private int age20_cmt;
    private int age30_cnt;
    private int age30_amt;
    private int age30_cmt;
    private int age40_cnt;
    private int age40_amt;
    private int age40_cmt;
    private int age50_cnt;
    private int age50_amt;
    private int age50_cmt;
    private int age60_cnt;
    private int age60_amt;
    private int age60_cmt;
    private int code01_cnt;
    private int code01_amt;
    private int code01_cmt;
    private int code02_cnt;
    private int code02_amt;
    private int code02_cmt;
    private int code03_cnt;
    private int code03_amt;
    private int code03_cmt;
    private int code04_cnt;
    private int code04_amt;
    private int code04_cmt;
    private int code05_cnt;
    private int code05_amt;
    private int code05_cmt;
    private int code06_cnt;
    private int code06_amt;
    private int code06_cmt;
    private int code07_cnt;
    private int code07_amt;
    private int code07_cmt;
    private int code08_cnt;
    private int code08_amt;
    private int code08_cmt;
    private int code09_cnt;
    private int code09_amt;
    private int code09_cmt;
    private int code10_cnt;
    private int code10_amt;
    private int code10_cmt;
    private int code11_cnt;
    private int code11_amt;
    private int code11_cmt;
    private int code12_cnt;
    private int code12_amt;
    private int code12_cmt;

    private int code13_cnt;
    private int code13_amt;
    private int code13_cmt;
    private int code14_cnt;
    private int code14_amt;
    private int code14_cmt;
    private int code15_cnt;
    private int code15_amt;
    private int code15_cmt;

    private int code16_cnt;
    private int code16_amt;
    private int code16_cmt;
    private int code17_cnt;
    private int code17_amt;
    private int code17_cmt;
    private int code18_cnt;
    private int code18_amt;
    private int code18_cmt;
    private int code19_cnt;
    private int code19_amt;
    private int code19_cmt;
    private int code20_cnt;
    private int code20_amt;
    private int code20_cmt;
    private int code21_cnt;
    private int code21_amt;
    private int code21_cmt;
    private int code22_cnt;
    private int code22_amt;
    private int code22_cmt;
    private int code23_cnt;
    private int code23_amt;
    private int code23_cmt;

    private int cancelCnt;
    private int cancelAmt;
    private int cancelCmt;



}
