package com.dalbit.enter.vo.procedure;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class P_PayCodeOutDetailVo {
    private String daily;
    private String monthly;
    private String date;
    private String hour;
    private int totalCnt;
    private int totalAmt;
    private int totalCmt;
    private int code01Cnt;
    private int code01Amt;
    private int code01Cmt;
    private int code02Cnt;
    private int code02Amt;
    private int code02Cmt;
    private int code03Cnt;
    private int code03Amt;
    private int code03Cmt;
    private int code04Cnt;
    private int code04Amt;
    private int code04Cmt;
    private int code05Cnt;
    private int code05Amt;
    private int code05Cmt;
    private int code06Cnt;
    private int code06Amt;
    private int code06Cmt;
    private int code07Cnt;
    private int code07Amt;
    private int code07Cmt;
    private int code08Cnt;
    private int code08Amt;
    private int code08Cmt;
    private int code09Cnt;
    private int code09Amt;
    private int code09Cmt;
    private int code10Cnt;
    private int code10Amt;
    private int code10Cmt;
    private int code11Cnt;
    private int code11Amt;
    private int code11Cmt;
    private int code12Cnt;
    private int code12Amt;
    private int code12Cmt;
    private int code13Cnt;
    private int code13Amt;
    private int code13Cmt;
    private int code14Cnt;
    private int code14Amt;
    private int code14Cmt;
    private int code15Cnt;
    private int code15Amt;
    private int code15Cmt;
    private int code16Cnt;
    private int code16Amt;
    private int code16Cmt;
    private int code17Cnt;
    private int code17Amt;
    private int code17Cmt;
    private int code18Cnt;
    private int code18Amt;
    private int code18Cmt;
    private int code19Cnt;
    private int code19Amt;
    private int code19Cmt;
    private int code20Cnt;
    private int code20Amt;
    private int code20Cmt;
    private int code21Cnt;
    private int code21Amt;
    private int code21Cmt;
    private int code22Cnt;
    private int code22Amt;
    private int code22Cmt;
    private int code23Cnt;
    private int code23Amt;
    private int code23Cmt;
}